# Ultima version de ubuntu 16.04
FROM ubuntu:16.04
# Se actualiza repositorios y paquetes
RUN apt-get update && yes|apt-get upgrade
# Se instalan librerias de desarrollo
RUN apt-get install -y python3 \ 
                    python-dev \ 
                    python3-dev \ 
                    build-essential \ 
                    libssl-dev \ 
                    libffi-dev \ 
                    libxml2-dev \ 
                    libxslt1-dev \ 
                    zlib1g-dev \ 
                    python-pip \ 
                    python3-pip \ 
                    graphviz \ 
                    libgraphviz-dev \ 
                    pkg-config \ 
                    git 
